addSbtPlugin("com.github.gseitz"  % "sbt-release"                   % "1.0.6")
addSbtPlugin("de.heikoseeberger"  % "sbt-header"                    % "3.0.1")
addSbtPlugin("org.foundweekends"  % "sbt-bintray"                   % "0.5.1")
addSbtPlugin("org.portable-scala" % "sbt-scalajs-crossproject"      % "0.6.0")
addSbtPlugin("org.portable-scala" % "sbt-scala-native-crossproject" % "0.6.0")
addSbtPlugin("org.scala-js"       % "sbt-scalajs"                   % "0.6.23")
addSbtPlugin("org.scala-native"   % "sbt-scala-native"              % "0.3.7")
addSbtPlugin("org.scalariform"    % "sbt-scalariform"               % "1.8.0")
